### ISSUE TITLE
DDRx drivers inside

### ISSUE THREAD

**Issue by emard** [hdl4fpga/hdl4fpga#2]
HI

I see there is not only scope inside but also open source
DDRx RAM driver.

Can there be some quick info about DDR driver, what
works what doesn't, list of memory chips known to work
and would DDR driver work for a small 32bit soft core CPU

**Comment by hdl4fpga** [comment]
I works with DDR1/2/3 I've tested it on spartan3e, spartan3a, virtex-5, artix and latticesemi ecp3.
You can check this release https://github.com/hdl4fpga/hdl4fpga/releases/tag/v0.0
