### ISSUE TITLE
oled geometry vtaxis 1 pixel off screen

### ISSUE THREAD

**Issue by emard** [hdl4fpga/hdl4fpga#230]
When OLED geometry is selected (ULX3S) then
vtaxis numbers line is 1 pixel out of screen on the left

**Comment by hdl4fpga** [comment]
I'll check

**Comment by emard** [comment]
this bug is still active
vtaxis_width     =>    8,
vttick_rotate    => ccw90,

**Comment by hdl4fpga** [comment]
Yes, I know ... That's why I didn't close the issue ... Can you provide me
with an image ?

**Comment by emard** [comment]
picture sent directly to your email

**Comment by hdl4fpga** [comment]
Fixed
