### ISSUE TITLE
ethernet to SPI

### ISSUE THREAD

**Issue by emard** [hdl4fpga/hdl4fpga#3]
Some boards don't have MII ethernet - can ethernet
controller be separated from scope with SPI bus interface inbetween.

So UDP control packet first gets buffered and with SPI bus sent to scope.

Then for example wireless IoT esp32 or esp8266 can be used instead of MII controller,
Not only UDP, they can even provide complete web interface to scope controls.

**Comment by hdl4fpga** [comment]
Yes, It is possible but in a few month. I am reworking it now
