### ISSUE TITLE
UDP ack

### ISSUE THREAD

**Issue by emard** [hdl4fpga/hdl4fpga#300]
On busy LAN packets often may be lost.

In practice it means that with hostmouse.py
every 10th mouse click is lost or misreceived,
a bit annoying to the user.

So I would propose - for each incoming packet to check
CRC and if CRC is OK, then echo-reply back to the sender the
same packet with correct CRC calculated.

If host doesn't receive same packet within some timeout,
it will re-send it few times, thus increasing UDP link reliability.

besides of UDP also ICMP can be used, that way scopeio will
respond to ping and with specially formatted packets it will
be controlled.same way as it was with UDP

**Comment by hdl4fpga** [comment]
Working on this now

**Comment by emard** [comment]
Aaaaaaa UDP ack!!!
It will be major speed improvement!

In the meantime I can check is ETH8720 module support still working for ULX3S

**Comment by hdl4fpga** [comment]
DONE!
