### ISSUE TITLE
arty syntax error

### ISSUE THREAD

**Issue by emard** [hdl4fpga/hdl4fpga#4]
HI

is the current status for artix-7, should the project compile?
currently I get some vivado syntax errors while trying to compile with vivado 2018.1

I don't have arty board but have some similar artix-7 board with MII chip
DP83848C, Is this chip likely to work?

Will scopeio mii ethernet implementation work if plugged into ethernet switch?
Should switch detect some cable presence and some ethernet speed?

**Comment by hdl4fpga** [comment]
This is the working release https://github.com/hdl4fpga/hdl4fpga/releases/tag/arty. The repository is not working now.

Scopeio should be independent of the mii chip. I tried it on different mii chips and in all of them worked.
All ethernet switches should work. I don't connect it directly to the computer. Send me a email to hdl4fpga@gmail.com.

Thanks
