### ISSUE TITLE
Posibility to use hdl4fpga on ULX3S board

### ISSUE THREAD

**Issue by goran-mahovlic** [hdl4fpga/hdl4fpga#6]
It would be so great if we could run hdl4fpga on ULX3S board!

https://hackaday.io/project/159108-ulx3s-powerful-ecp5-board-for-open-source-fpga

**Comment by hdl4fpga** [comment]
Working on it. Contact me at https://discord.gg/qMBGW6A on discord

**Comment by goran-mahovlic** [comment]
Great!
Thank you!
I am at work will contact you when I get home...
