### ISSUE TITLE
Mouse control

### ISSUE THREAD

**Issue by emard** [hdl4fpga/hdl4fpga#7]
A suggestion to improve easy and interactive use of the oscilloscope:

use PS/2 mouse which draws XY crosshair pointer on VGA screen.
Here is a simple point-and-click-to-change example:
https://github.com/emard/ulx3s-misc/tree/master/examples/ps2/mouse_dvi_gui/proj/lattice/ulx3s

clicking and/or dragging on selected positions on the grid
or on the names of channel controls will change parameters

**Comment by hdl4fpga** [comment]
It is one of things to do ... they so many XD
